### ISSUE TITLE
Command output not usable in web_acl 

### ISSUE THREAD

**Issue by PierreRAFFA** [matti/terraform-shell-outputs#1]
Hi,
I am using this module to retrieve a http_rate_based_rule using aws cli because terraform does not provide a way to get it.
The output prints the correct value but I can not use the command output in web_acl as I got `aws_waf_web_acl.waf_acl: aws_waf_web_acl.waf_acl: diffs didn't match during apply.` on apply.

FYI, if I set `rule_id` to the expected value it works. So it's like the output is not something that terraform can use.
Any idea ?

```tf
module "http_rate_limit_rule_id" {
  source  = "matti/outputs/shell"
  version = "0.1.2"
  command = "aws waf list-rate-based-rules --query 'Rules[?Name==`rate-limit-2k`].RuleId' --output text"
}

output "mycmd" {
  value = {
    stdout      = "${module.http_rate_limit_rule_id.stdout}"
    stderr      = "${module.http_rate_limit_rule_id.stderr}"
  }
}

resource "aws_waf_web_acl" "waf_acl" {
  depends_on = ["module.http_rate_limit_rule_id"]

  name        = "${local.web_acl_name}"
  //just alpha-numeric allowed here
  metric_name = "${local.metric_name}"

  default_action {
    type = "ALLOW"
  }

  rules {
    action {
      type = "BLOCK"
    }

    priority = 1
    rule_id  = "${module.http_rate_limit_rule_id.stdout}"    <== output used here
    type     = "RATE_BASED"
  }
}


```

**Comment by matti** [comment]
archiving this project in favor of https://github.com/Invicton-Labs/terraform-external-shell-resource and https://github.com/Invicton-Labs/terraform-external-shell-data
